// Code generated by girgen for GLib-2. DO NOT EDIT.

package glib

import (
	"unsafe"

	"github.com/go-gst/go-glib/pkg/core/userdata"
)

// #include <glib.h>
import "C"

//export _goglib_glib2_LogFunc
func _goglib_glib2_LogFunc(carg1 *C.gchar, carg2 C.GLogLevelFlags, carg3 *C.gchar, carg4 C.gpointer) {
	var fn LogFunc
	{
		v := userdata.Load(unsafe.Pointer(carg4))
		if v == nil {
			panic(`callback not found`)
		}
		fn = v.(LogFunc)
	}

	var logDomain string        // in, none, string, nullable-string
	var logLevel  LogLevelFlags // in, none, casted
	var message   string        // in, none, string

	if carg1 != nil {
		logDomain = C.GoString((*C.char)(unsafe.Pointer(carg1)))
	}
	logLevel = LogLevelFlags(carg2)
	message = C.GoString((*C.char)(unsafe.Pointer(carg3)))

	fn(logDomain, logLevel, message)
}

//export _goglib_glib2_LogWriterFunc
func _goglib_glib2_LogWriterFunc(carg1 C.GLogLevelFlags, carg2 *C.GLogField, carg3 C.gsize, carg4 C.gpointer) (cret C.GLogWriterOutput) {
	var fn LogWriterFunc
	{
		v := userdata.Load(unsafe.Pointer(carg4))
		if v == nil {
			panic(`callback not found`)
		}
		fn = v.(LogWriterFunc)
	}

	var logLevel LogLevelFlags   // in, none, casted
	var fields   []LogField      // in, transfer: none, C Pointers: 1, Name: array[LogField], array (inner GLogField (*typesystem.Record), length-by: carg3)
	var goret    LogWriterOutput // return, none, casted

	logLevel = LogLevelFlags(carg1)
	_ = fields
	_ = carg2
	_ = carg3
	panic("unimplemented conversion of []LogField (const GLogField*) because of unknown reason")

	goret = fn(logLevel, fields)

	cret = C.GLogWriterOutput(goret)

	return cret
}

//export _goglib_glib2_SourceFunc
func _goglib_glib2_SourceFunc(carg1 C.gpointer) (cret C.gboolean) {
	var fn SourceFunc
	{
		v := userdata.Load(unsafe.Pointer(carg1))
		if v == nil {
			panic(`callback not found`)
		}
		fn = v.(SourceFunc)
	}

	var goret bool // return

	goret = fn()

	if goret {
		cret = C.TRUE
	}

	return cret
}

//export _goglib_glib2_SourceOnceFunc
func _goglib_glib2_SourceOnceFunc(carg1 C.gpointer) {
	var fn SourceOnceFunc
	{
		v := userdata.Load(unsafe.Pointer(carg1))
		if v == nil {
			panic(`callback not found`)
		}
		fn = v.(SourceOnceFunc)
	}

	fn()
}

//export _goglib_glib2_TestDataFunc
func _goglib_glib2_TestDataFunc(carg1 C.gconstpointer) {
	var fn TestDataFunc
	{
		v := userdata.Load(unsafe.Pointer(carg1))
		if v == nil {
			panic(`callback not found`)
		}
		fn = v.(TestDataFunc)
	}

	fn()
}

//export _goglib_glib2_TestLogFatalFunc
func _goglib_glib2_TestLogFatalFunc(carg1 *C.gchar, carg2 C.GLogLevelFlags, carg3 *C.gchar, carg4 C.gpointer) (cret C.gboolean) {
	var fn TestLogFatalFunc
	{
		v := userdata.Load(unsafe.Pointer(carg4))
		if v == nil {
			panic(`callback not found`)
		}
		fn = v.(TestLogFatalFunc)
	}

	var logDomain string        // in, none, string
	var logLevel  LogLevelFlags // in, none, casted
	var message   string        // in, none, string
	var goret     bool          // return

	logDomain = C.GoString((*C.char)(unsafe.Pointer(carg1)))
	logLevel = LogLevelFlags(carg2)
	message = C.GoString((*C.char)(unsafe.Pointer(carg3)))

	goret = fn(logDomain, logLevel, message)

	if goret {
		cret = C.TRUE
	}

	return cret
}

