// Code generated by girgen for Gio-2. DO NOT EDIT.

package gio

import (
	"unsafe"

	"github.com/go-gst/go-glib/pkg/core/classdata"
	"github.com/go-gst/go-glib/pkg/core/userdata"
	"github.com/go-gst/go-glib/pkg/gobject/v2"
)

// #include <gio/gio.h>
import "C"

//export _goglib_gio2_AsyncReadyCallback
func _goglib_gio2_AsyncReadyCallback(carg1 *C.GObject, carg2 *C.GAsyncResult, carg3 C.gpointer) {
	var fn AsyncReadyCallback
	{
		v := userdata.Load(unsafe.Pointer(carg3))
		if v == nil {
			panic(`callback not found`)
		}
		fn = v.(AsyncReadyCallback)
	}

	var sourceObject gobject.Object // in, none, converted, nullable
	var res          AsyncResult    // in, none, converted

	if carg1 != nil {
		sourceObject = gobject.UnsafeObjectFromGlibNone(unsafe.Pointer(carg1))
	}
	res = UnsafeAsyncResultFromGlibNone(unsafe.Pointer(carg2))

	fn(sourceObject, res)
}

//export _goglib_gio2_VfsFileLookupFunc
func _goglib_gio2_VfsFileLookupFunc(carg1 *C.GVfs, carg2 *C.char, carg3 C.gpointer) (cret *C.GFile) {
	var fn VfsFileLookupFunc
	{
		v := userdata.Load(unsafe.Pointer(carg3))
		if v == nil {
			panic(`callback not found`)
		}
		fn = v.(VfsFileLookupFunc)
	}

	var vfs        Vfs    // in, none, converted
	var identifier string // in, none, string
	var goret      File   // return, full, converted, nullable

	vfs = UnsafeVfsFromGlibNone(unsafe.Pointer(carg1))
	identifier = C.GoString((*C.char)(unsafe.Pointer(carg2)))

	goret = fn(vfs, identifier)

	if goret != nil {
		cret = (*C.GFile)(UnsafeFileToGlibFull(goret))
	}

	return cret
}

//export _goglib_gio2_AppLaunchContext_launch_failed
func _goglib_gio2_AppLaunchContext_launch_failed(carg0 *C.GAppLaunchContext, carg1 *C.char) {
	var fn func(carg0 *C.GAppLaunchContext, carg1 *C.char)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_AppLaunchContext_launch_failed").(func(carg0 *C.GAppLaunchContext, carg1 *C.char))
		if fn == nil {
			panic("_goglib_gio2_AppLaunchContext_launch_failed: no function pointer found")
		}
	}
	fn(carg0, carg1)
}

//export _goglib_gio2_Application_activate
func _goglib_gio2_Application_activate(carg0 *C.GApplication) {
	var fn func(carg0 *C.GApplication)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_Application_activate").(func(carg0 *C.GApplication))
		if fn == nil {
			panic("_goglib_gio2_Application_activate: no function pointer found")
		}
	}
	fn(carg0)
}

//export _goglib_gio2_Application_add_platform_data
func _goglib_gio2_Application_add_platform_data(carg0 *C.GApplication, carg1 *C.GVariantBuilder) {
	var fn func(carg0 *C.GApplication, carg1 *C.GVariantBuilder)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_Application_add_platform_data").(func(carg0 *C.GApplication, carg1 *C.GVariantBuilder))
		if fn == nil {
			panic("_goglib_gio2_Application_add_platform_data: no function pointer found")
		}
	}
	fn(carg0, carg1)
}

//export _goglib_gio2_Application_command_line
func _goglib_gio2_Application_command_line(carg0 *C.GApplication, carg1 *C.GApplicationCommandLine) (cret C.int) {
	var fn func(carg0 *C.GApplication, carg1 *C.GApplicationCommandLine) (cret C.int)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_Application_command_line").(func(carg0 *C.GApplication, carg1 *C.GApplicationCommandLine) (cret C.int))
		if fn == nil {
			panic("_goglib_gio2_Application_command_line: no function pointer found")
		}
	}
	return fn(carg0, carg1)
}

//export _goglib_gio2_Application_handle_local_options
func _goglib_gio2_Application_handle_local_options(carg0 *C.GApplication, carg1 *C.GVariantDict) (cret C.gint) {
	var fn func(carg0 *C.GApplication, carg1 *C.GVariantDict) (cret C.gint)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_Application_handle_local_options").(func(carg0 *C.GApplication, carg1 *C.GVariantDict) (cret C.gint))
		if fn == nil {
			panic("_goglib_gio2_Application_handle_local_options: no function pointer found")
		}
	}
	return fn(carg0, carg1)
}

//export _goglib_gio2_Application_name_lost
func _goglib_gio2_Application_name_lost(carg0 *C.GApplication) (cret C.gboolean) {
	var fn func(carg0 *C.GApplication) (cret C.gboolean)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_Application_name_lost").(func(carg0 *C.GApplication) (cret C.gboolean))
		if fn == nil {
			panic("_goglib_gio2_Application_name_lost: no function pointer found")
		}
	}
	return fn(carg0)
}

//export _goglib_gio2_Application_open
func _goglib_gio2_Application_open(carg0 *C.GApplication, carg1 **C.GFile, carg2 C.gint, carg3 *C.gchar) {
	var fn func(carg0 *C.GApplication, carg1 **C.GFile, carg2 C.gint, carg3 *C.gchar)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_Application_open").(func(carg0 *C.GApplication, carg1 **C.GFile, carg2 C.gint, carg3 *C.gchar))
		if fn == nil {
			panic("_goglib_gio2_Application_open: no function pointer found")
		}
	}
	fn(carg0, carg1, carg2, carg3)
}

//export _goglib_gio2_Application_quit_mainloop
func _goglib_gio2_Application_quit_mainloop(carg0 *C.GApplication) {
	var fn func(carg0 *C.GApplication)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_Application_quit_mainloop").(func(carg0 *C.GApplication))
		if fn == nil {
			panic("_goglib_gio2_Application_quit_mainloop: no function pointer found")
		}
	}
	fn(carg0)
}

//export _goglib_gio2_Application_run_mainloop
func _goglib_gio2_Application_run_mainloop(carg0 *C.GApplication) {
	var fn func(carg0 *C.GApplication)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_Application_run_mainloop").(func(carg0 *C.GApplication))
		if fn == nil {
			panic("_goglib_gio2_Application_run_mainloop: no function pointer found")
		}
	}
	fn(carg0)
}

//export _goglib_gio2_Application_shutdown
func _goglib_gio2_Application_shutdown(carg0 *C.GApplication) {
	var fn func(carg0 *C.GApplication)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_Application_shutdown").(func(carg0 *C.GApplication))
		if fn == nil {
			panic("_goglib_gio2_Application_shutdown: no function pointer found")
		}
	}
	fn(carg0)
}

//export _goglib_gio2_Application_startup
func _goglib_gio2_Application_startup(carg0 *C.GApplication) {
	var fn func(carg0 *C.GApplication)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_Application_startup").(func(carg0 *C.GApplication))
		if fn == nil {
			panic("_goglib_gio2_Application_startup: no function pointer found")
		}
	}
	fn(carg0)
}

//export _goglib_gio2_ApplicationCommandLine_done
func _goglib_gio2_ApplicationCommandLine_done(carg0 *C.GApplicationCommandLine) {
	var fn func(carg0 *C.GApplicationCommandLine)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_ApplicationCommandLine_done").(func(carg0 *C.GApplicationCommandLine))
		if fn == nil {
			panic("_goglib_gio2_ApplicationCommandLine_done: no function pointer found")
		}
	}
	fn(carg0)
}

//export _goglib_gio2_ApplicationCommandLine_get_stdin
func _goglib_gio2_ApplicationCommandLine_get_stdin(carg0 *C.GApplicationCommandLine) (cret *C.GInputStream) {
	var fn func(carg0 *C.GApplicationCommandLine) (cret *C.GInputStream)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_ApplicationCommandLine_get_stdin").(func(carg0 *C.GApplicationCommandLine) (cret *C.GInputStream))
		if fn == nil {
			panic("_goglib_gio2_ApplicationCommandLine_get_stdin: no function pointer found")
		}
	}
	return fn(carg0)
}

//export _goglib_gio2_ApplicationCommandLine_print_literal
func _goglib_gio2_ApplicationCommandLine_print_literal(carg0 *C.GApplicationCommandLine, carg1 *C.gchar) {
	var fn func(carg0 *C.GApplicationCommandLine, carg1 *C.gchar)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_ApplicationCommandLine_print_literal").(func(carg0 *C.GApplicationCommandLine, carg1 *C.gchar))
		if fn == nil {
			panic("_goglib_gio2_ApplicationCommandLine_print_literal: no function pointer found")
		}
	}
	fn(carg0, carg1)
}

//export _goglib_gio2_ApplicationCommandLine_printerr_literal
func _goglib_gio2_ApplicationCommandLine_printerr_literal(carg0 *C.GApplicationCommandLine, carg1 *C.gchar) {
	var fn func(carg0 *C.GApplicationCommandLine, carg1 *C.gchar)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_ApplicationCommandLine_printerr_literal").(func(carg0 *C.GApplicationCommandLine, carg1 *C.gchar))
		if fn == nil {
			panic("_goglib_gio2_ApplicationCommandLine_printerr_literal: no function pointer found")
		}
	}
	fn(carg0, carg1)
}

//export _goglib_gio2_Cancellable_cancelled
func _goglib_gio2_Cancellable_cancelled(carg0 *C.GCancellable) {
	var fn func(carg0 *C.GCancellable)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_Cancellable_cancelled").(func(carg0 *C.GCancellable))
		if fn == nil {
			panic("_goglib_gio2_Cancellable_cancelled: no function pointer found")
		}
	}
	fn(carg0)
}

//export _goglib_gio2_FileEnumerator_close_finish
func _goglib_gio2_FileEnumerator_close_finish(carg0 *C.GFileEnumerator, carg1 *C.GAsyncResult, _cerr **C.GError) (cret C.gboolean) {
	var fn func(carg0 *C.GFileEnumerator, carg1 *C.GAsyncResult, _cerr **C.GError) (cret C.gboolean)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_FileEnumerator_close_finish").(func(carg0 *C.GFileEnumerator, carg1 *C.GAsyncResult, _cerr **C.GError) (cret C.gboolean))
		if fn == nil {
			panic("_goglib_gio2_FileEnumerator_close_finish: no function pointer found")
		}
	}
	return fn(carg0, carg1, _cerr)
}

//export _goglib_gio2_FileEnumerator_close_fn
func _goglib_gio2_FileEnumerator_close_fn(carg0 *C.GFileEnumerator, carg1 *C.GCancellable, _cerr **C.GError) (cret C.gboolean) {
	var fn func(carg0 *C.GFileEnumerator, carg1 *C.GCancellable, _cerr **C.GError) (cret C.gboolean)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_FileEnumerator_close_fn").(func(carg0 *C.GFileEnumerator, carg1 *C.GCancellable, _cerr **C.GError) (cret C.gboolean))
		if fn == nil {
			panic("_goglib_gio2_FileEnumerator_close_fn: no function pointer found")
		}
	}
	return fn(carg0, carg1, _cerr)
}

//export _goglib_gio2_FileEnumerator_next_file
func _goglib_gio2_FileEnumerator_next_file(carg0 *C.GFileEnumerator, carg1 *C.GCancellable, _cerr **C.GError) (cret *C.GFileInfo) {
	var fn func(carg0 *C.GFileEnumerator, carg1 *C.GCancellable, _cerr **C.GError) (cret *C.GFileInfo)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_FileEnumerator_next_file").(func(carg0 *C.GFileEnumerator, carg1 *C.GCancellable, _cerr **C.GError) (cret *C.GFileInfo))
		if fn == nil {
			panic("_goglib_gio2_FileEnumerator_next_file: no function pointer found")
		}
	}
	return fn(carg0, carg1, _cerr)
}

//export _goglib_gio2_FileEnumerator_next_files_finish
func _goglib_gio2_FileEnumerator_next_files_finish(carg0 *C.GFileEnumerator, carg1 *C.GAsyncResult, _cerr **C.GError) (cret *C.GList) {
	var fn func(carg0 *C.GFileEnumerator, carg1 *C.GAsyncResult, _cerr **C.GError) (cret *C.GList)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_FileEnumerator_next_files_finish").(func(carg0 *C.GFileEnumerator, carg1 *C.GAsyncResult, _cerr **C.GError) (cret *C.GList))
		if fn == nil {
			panic("_goglib_gio2_FileEnumerator_next_files_finish: no function pointer found")
		}
	}
	return fn(carg0, carg1, _cerr)
}

//export _goglib_gio2_FileMonitor_cancel
func _goglib_gio2_FileMonitor_cancel(carg0 *C.GFileMonitor) (cret C.gboolean) {
	var fn func(carg0 *C.GFileMonitor) (cret C.gboolean)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_FileMonitor_cancel").(func(carg0 *C.GFileMonitor) (cret C.gboolean))
		if fn == nil {
			panic("_goglib_gio2_FileMonitor_cancel: no function pointer found")
		}
	}
	return fn(carg0)
}

//export _goglib_gio2_FileMonitor_changed
func _goglib_gio2_FileMonitor_changed(carg0 *C.GFileMonitor, carg1 *C.GFile, carg2 *C.GFile, carg3 C.GFileMonitorEvent) {
	var fn func(carg0 *C.GFileMonitor, carg1 *C.GFile, carg2 *C.GFile, carg3 C.GFileMonitorEvent)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_FileMonitor_changed").(func(carg0 *C.GFileMonitor, carg1 *C.GFile, carg2 *C.GFile, carg3 C.GFileMonitorEvent))
		if fn == nil {
			panic("_goglib_gio2_FileMonitor_changed: no function pointer found")
		}
	}
	fn(carg0, carg1, carg2, carg3)
}

//export _goglib_gio2_FilenameCompleter_got_completion_data
func _goglib_gio2_FilenameCompleter_got_completion_data(carg0 *C.GFilenameCompleter) {
	var fn func(carg0 *C.GFilenameCompleter)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_FilenameCompleter_got_completion_data").(func(carg0 *C.GFilenameCompleter))
		if fn == nil {
			panic("_goglib_gio2_FilenameCompleter_got_completion_data: no function pointer found")
		}
	}
	fn(carg0)
}

//export _goglib_gio2_IOStream_close_finish
func _goglib_gio2_IOStream_close_finish(carg0 *C.GIOStream, carg1 *C.GAsyncResult, _cerr **C.GError) (cret C.gboolean) {
	var fn func(carg0 *C.GIOStream, carg1 *C.GAsyncResult, _cerr **C.GError) (cret C.gboolean)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_IOStream_close_finish").(func(carg0 *C.GIOStream, carg1 *C.GAsyncResult, _cerr **C.GError) (cret C.gboolean))
		if fn == nil {
			panic("_goglib_gio2_IOStream_close_finish: no function pointer found")
		}
	}
	return fn(carg0, carg1, _cerr)
}

//export _goglib_gio2_IOStream_close_fn
func _goglib_gio2_IOStream_close_fn(carg0 *C.GIOStream, carg1 *C.GCancellable, _cerr **C.GError) (cret C.gboolean) {
	var fn func(carg0 *C.GIOStream, carg1 *C.GCancellable, _cerr **C.GError) (cret C.gboolean)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_IOStream_close_fn").(func(carg0 *C.GIOStream, carg1 *C.GCancellable, _cerr **C.GError) (cret C.gboolean))
		if fn == nil {
			panic("_goglib_gio2_IOStream_close_fn: no function pointer found")
		}
	}
	return fn(carg0, carg1, _cerr)
}

//export _goglib_gio2_IOStream_get_input_stream
func _goglib_gio2_IOStream_get_input_stream(carg0 *C.GIOStream) (cret *C.GInputStream) {
	var fn func(carg0 *C.GIOStream) (cret *C.GInputStream)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_IOStream_get_input_stream").(func(carg0 *C.GIOStream) (cret *C.GInputStream))
		if fn == nil {
			panic("_goglib_gio2_IOStream_get_input_stream: no function pointer found")
		}
	}
	return fn(carg0)
}

//export _goglib_gio2_IOStream_get_output_stream
func _goglib_gio2_IOStream_get_output_stream(carg0 *C.GIOStream) (cret *C.GOutputStream) {
	var fn func(carg0 *C.GIOStream) (cret *C.GOutputStream)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_IOStream_get_output_stream").(func(carg0 *C.GIOStream) (cret *C.GOutputStream))
		if fn == nil {
			panic("_goglib_gio2_IOStream_get_output_stream: no function pointer found")
		}
	}
	return fn(carg0)
}

//export _goglib_gio2_InputStream_close_finish
func _goglib_gio2_InputStream_close_finish(carg0 *C.GInputStream, carg1 *C.GAsyncResult, _cerr **C.GError) (cret C.gboolean) {
	var fn func(carg0 *C.GInputStream, carg1 *C.GAsyncResult, _cerr **C.GError) (cret C.gboolean)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_InputStream_close_finish").(func(carg0 *C.GInputStream, carg1 *C.GAsyncResult, _cerr **C.GError) (cret C.gboolean))
		if fn == nil {
			panic("_goglib_gio2_InputStream_close_finish: no function pointer found")
		}
	}
	return fn(carg0, carg1, _cerr)
}

//export _goglib_gio2_InputStream_close_fn
func _goglib_gio2_InputStream_close_fn(carg0 *C.GInputStream, carg1 *C.GCancellable, _cerr **C.GError) (cret C.gboolean) {
	var fn func(carg0 *C.GInputStream, carg1 *C.GCancellable, _cerr **C.GError) (cret C.gboolean)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_InputStream_close_fn").(func(carg0 *C.GInputStream, carg1 *C.GCancellable, _cerr **C.GError) (cret C.gboolean))
		if fn == nil {
			panic("_goglib_gio2_InputStream_close_fn: no function pointer found")
		}
	}
	return fn(carg0, carg1, _cerr)
}

//export _goglib_gio2_InputStream_read_finish
func _goglib_gio2_InputStream_read_finish(carg0 *C.GInputStream, carg1 *C.GAsyncResult, _cerr **C.GError) (cret C.gssize) {
	var fn func(carg0 *C.GInputStream, carg1 *C.GAsyncResult, _cerr **C.GError) (cret C.gssize)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_InputStream_read_finish").(func(carg0 *C.GInputStream, carg1 *C.GAsyncResult, _cerr **C.GError) (cret C.gssize))
		if fn == nil {
			panic("_goglib_gio2_InputStream_read_finish: no function pointer found")
		}
	}
	return fn(carg0, carg1, _cerr)
}

//export _goglib_gio2_InputStream_skip
func _goglib_gio2_InputStream_skip(carg0 *C.GInputStream, carg1 C.gsize, carg2 *C.GCancellable, _cerr **C.GError) (cret C.gssize) {
	var fn func(carg0 *C.GInputStream, carg1 C.gsize, carg2 *C.GCancellable, _cerr **C.GError) (cret C.gssize)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_InputStream_skip").(func(carg0 *C.GInputStream, carg1 C.gsize, carg2 *C.GCancellable, _cerr **C.GError) (cret C.gssize))
		if fn == nil {
			panic("_goglib_gio2_InputStream_skip: no function pointer found")
		}
	}
	return fn(carg0, carg1, carg2, _cerr)
}

//export _goglib_gio2_InputStream_skip_finish
func _goglib_gio2_InputStream_skip_finish(carg0 *C.GInputStream, carg1 *C.GAsyncResult, _cerr **C.GError) (cret C.gssize) {
	var fn func(carg0 *C.GInputStream, carg1 *C.GAsyncResult, _cerr **C.GError) (cret C.gssize)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_InputStream_skip_finish").(func(carg0 *C.GInputStream, carg1 *C.GAsyncResult, _cerr **C.GError) (cret C.gssize))
		if fn == nil {
			panic("_goglib_gio2_InputStream_skip_finish: no function pointer found")
		}
	}
	return fn(carg0, carg1, _cerr)
}

//export _goglib_gio2_MenuLinkIter_get_next
func _goglib_gio2_MenuLinkIter_get_next(carg0 *C.GMenuLinkIter, carg1 **C.gchar, carg2 **C.GMenuModel) (cret C.gboolean) {
	var fn func(carg0 *C.GMenuLinkIter, carg1 **C.gchar, carg2 **C.GMenuModel) (cret C.gboolean)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_MenuLinkIter_get_next").(func(carg0 *C.GMenuLinkIter, carg1 **C.gchar, carg2 **C.GMenuModel) (cret C.gboolean))
		if fn == nil {
			panic("_goglib_gio2_MenuLinkIter_get_next: no function pointer found")
		}
	}
	return fn(carg0, carg1, carg2)
}

//export _goglib_gio2_MenuModel_get_item_link
func _goglib_gio2_MenuModel_get_item_link(carg0 *C.GMenuModel, carg1 C.gint, carg2 *C.gchar) (cret *C.GMenuModel) {
	var fn func(carg0 *C.GMenuModel, carg1 C.gint, carg2 *C.gchar) (cret *C.GMenuModel)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_MenuModel_get_item_link").(func(carg0 *C.GMenuModel, carg1 C.gint, carg2 *C.gchar) (cret *C.GMenuModel))
		if fn == nil {
			panic("_goglib_gio2_MenuModel_get_item_link: no function pointer found")
		}
	}
	return fn(carg0, carg1, carg2)
}

//export _goglib_gio2_MenuModel_get_n_items
func _goglib_gio2_MenuModel_get_n_items(carg0 *C.GMenuModel) (cret C.gint) {
	var fn func(carg0 *C.GMenuModel) (cret C.gint)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_MenuModel_get_n_items").(func(carg0 *C.GMenuModel) (cret C.gint))
		if fn == nil {
			panic("_goglib_gio2_MenuModel_get_n_items: no function pointer found")
		}
	}
	return fn(carg0)
}

//export _goglib_gio2_MenuModel_is_mutable
func _goglib_gio2_MenuModel_is_mutable(carg0 *C.GMenuModel) (cret C.gboolean) {
	var fn func(carg0 *C.GMenuModel) (cret C.gboolean)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_MenuModel_is_mutable").(func(carg0 *C.GMenuModel) (cret C.gboolean))
		if fn == nil {
			panic("_goglib_gio2_MenuModel_is_mutable: no function pointer found")
		}
	}
	return fn(carg0)
}

//export _goglib_gio2_MenuModel_iterate_item_attributes
func _goglib_gio2_MenuModel_iterate_item_attributes(carg0 *C.GMenuModel, carg1 C.gint) (cret *C.GMenuAttributeIter) {
	var fn func(carg0 *C.GMenuModel, carg1 C.gint) (cret *C.GMenuAttributeIter)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_MenuModel_iterate_item_attributes").(func(carg0 *C.GMenuModel, carg1 C.gint) (cret *C.GMenuAttributeIter))
		if fn == nil {
			panic("_goglib_gio2_MenuModel_iterate_item_attributes: no function pointer found")
		}
	}
	return fn(carg0, carg1)
}

//export _goglib_gio2_MenuModel_iterate_item_links
func _goglib_gio2_MenuModel_iterate_item_links(carg0 *C.GMenuModel, carg1 C.gint) (cret *C.GMenuLinkIter) {
	var fn func(carg0 *C.GMenuModel, carg1 C.gint) (cret *C.GMenuLinkIter)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_MenuModel_iterate_item_links").(func(carg0 *C.GMenuModel, carg1 C.gint) (cret *C.GMenuLinkIter))
		if fn == nil {
			panic("_goglib_gio2_MenuModel_iterate_item_links: no function pointer found")
		}
	}
	return fn(carg0, carg1)
}

//export _goglib_gio2_MountOperation_aborted
func _goglib_gio2_MountOperation_aborted(carg0 *C.GMountOperation) {
	var fn func(carg0 *C.GMountOperation)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_MountOperation_aborted").(func(carg0 *C.GMountOperation))
		if fn == nil {
			panic("_goglib_gio2_MountOperation_aborted: no function pointer found")
		}
	}
	fn(carg0)
}

//export _goglib_gio2_MountOperation_ask_password
func _goglib_gio2_MountOperation_ask_password(carg0 *C.GMountOperation, carg1 *C.char, carg2 *C.char, carg3 *C.char, carg4 C.GAskPasswordFlags) {
	var fn func(carg0 *C.GMountOperation, carg1 *C.char, carg2 *C.char, carg3 *C.char, carg4 C.GAskPasswordFlags)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_MountOperation_ask_password").(func(carg0 *C.GMountOperation, carg1 *C.char, carg2 *C.char, carg3 *C.char, carg4 C.GAskPasswordFlags))
		if fn == nil {
			panic("_goglib_gio2_MountOperation_ask_password: no function pointer found")
		}
	}
	fn(carg0, carg1, carg2, carg3, carg4)
}

//export _goglib_gio2_MountOperation_ask_question
func _goglib_gio2_MountOperation_ask_question(carg0 *C.GMountOperation, carg1 *C.char, carg2 **C.char) {
	var fn func(carg0 *C.GMountOperation, carg1 *C.char, carg2 **C.char)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_MountOperation_ask_question").(func(carg0 *C.GMountOperation, carg1 *C.char, carg2 **C.char))
		if fn == nil {
			panic("_goglib_gio2_MountOperation_ask_question: no function pointer found")
		}
	}
	fn(carg0, carg1, carg2)
}

//export _goglib_gio2_MountOperation_reply
func _goglib_gio2_MountOperation_reply(carg0 *C.GMountOperation, carg1 C.GMountOperationResult) {
	var fn func(carg0 *C.GMountOperation, carg1 C.GMountOperationResult)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_MountOperation_reply").(func(carg0 *C.GMountOperation, carg1 C.GMountOperationResult))
		if fn == nil {
			panic("_goglib_gio2_MountOperation_reply: no function pointer found")
		}
	}
	fn(carg0, carg1)
}

//export _goglib_gio2_MountOperation_show_unmount_progress
func _goglib_gio2_MountOperation_show_unmount_progress(carg0 *C.GMountOperation, carg1 *C.gchar, carg2 C.gint64, carg3 C.gint64) {
	var fn func(carg0 *C.GMountOperation, carg1 *C.gchar, carg2 C.gint64, carg3 C.gint64)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_MountOperation_show_unmount_progress").(func(carg0 *C.GMountOperation, carg1 *C.gchar, carg2 C.gint64, carg3 C.gint64))
		if fn == nil {
			panic("_goglib_gio2_MountOperation_show_unmount_progress: no function pointer found")
		}
	}
	fn(carg0, carg1, carg2, carg3)
}

//export _goglib_gio2_OutputStream_close_finish
func _goglib_gio2_OutputStream_close_finish(carg0 *C.GOutputStream, carg1 *C.GAsyncResult, _cerr **C.GError) (cret C.gboolean) {
	var fn func(carg0 *C.GOutputStream, carg1 *C.GAsyncResult, _cerr **C.GError) (cret C.gboolean)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_OutputStream_close_finish").(func(carg0 *C.GOutputStream, carg1 *C.GAsyncResult, _cerr **C.GError) (cret C.gboolean))
		if fn == nil {
			panic("_goglib_gio2_OutputStream_close_finish: no function pointer found")
		}
	}
	return fn(carg0, carg1, _cerr)
}

//export _goglib_gio2_OutputStream_close_fn
func _goglib_gio2_OutputStream_close_fn(carg0 *C.GOutputStream, carg1 *C.GCancellable, _cerr **C.GError) (cret C.gboolean) {
	var fn func(carg0 *C.GOutputStream, carg1 *C.GCancellable, _cerr **C.GError) (cret C.gboolean)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_OutputStream_close_fn").(func(carg0 *C.GOutputStream, carg1 *C.GCancellable, _cerr **C.GError) (cret C.gboolean))
		if fn == nil {
			panic("_goglib_gio2_OutputStream_close_fn: no function pointer found")
		}
	}
	return fn(carg0, carg1, _cerr)
}

//export _goglib_gio2_OutputStream_flush
func _goglib_gio2_OutputStream_flush(carg0 *C.GOutputStream, carg1 *C.GCancellable, _cerr **C.GError) (cret C.gboolean) {
	var fn func(carg0 *C.GOutputStream, carg1 *C.GCancellable, _cerr **C.GError) (cret C.gboolean)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_OutputStream_flush").(func(carg0 *C.GOutputStream, carg1 *C.GCancellable, _cerr **C.GError) (cret C.gboolean))
		if fn == nil {
			panic("_goglib_gio2_OutputStream_flush: no function pointer found")
		}
	}
	return fn(carg0, carg1, _cerr)
}

//export _goglib_gio2_OutputStream_flush_finish
func _goglib_gio2_OutputStream_flush_finish(carg0 *C.GOutputStream, carg1 *C.GAsyncResult, _cerr **C.GError) (cret C.gboolean) {
	var fn func(carg0 *C.GOutputStream, carg1 *C.GAsyncResult, _cerr **C.GError) (cret C.gboolean)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_OutputStream_flush_finish").(func(carg0 *C.GOutputStream, carg1 *C.GAsyncResult, _cerr **C.GError) (cret C.gboolean))
		if fn == nil {
			panic("_goglib_gio2_OutputStream_flush_finish: no function pointer found")
		}
	}
	return fn(carg0, carg1, _cerr)
}

//export _goglib_gio2_OutputStream_splice
func _goglib_gio2_OutputStream_splice(carg0 *C.GOutputStream, carg1 *C.GInputStream, carg2 C.GOutputStreamSpliceFlags, carg3 *C.GCancellable, _cerr **C.GError) (cret C.gssize) {
	var fn func(carg0 *C.GOutputStream, carg1 *C.GInputStream, carg2 C.GOutputStreamSpliceFlags, carg3 *C.GCancellable, _cerr **C.GError) (cret C.gssize)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_OutputStream_splice").(func(carg0 *C.GOutputStream, carg1 *C.GInputStream, carg2 C.GOutputStreamSpliceFlags, carg3 *C.GCancellable, _cerr **C.GError) (cret C.gssize))
		if fn == nil {
			panic("_goglib_gio2_OutputStream_splice: no function pointer found")
		}
	}
	return fn(carg0, carg1, carg2, carg3, _cerr)
}

//export _goglib_gio2_OutputStream_splice_finish
func _goglib_gio2_OutputStream_splice_finish(carg0 *C.GOutputStream, carg1 *C.GAsyncResult, _cerr **C.GError) (cret C.gssize) {
	var fn func(carg0 *C.GOutputStream, carg1 *C.GAsyncResult, _cerr **C.GError) (cret C.gssize)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_OutputStream_splice_finish").(func(carg0 *C.GOutputStream, carg1 *C.GAsyncResult, _cerr **C.GError) (cret C.gssize))
		if fn == nil {
			panic("_goglib_gio2_OutputStream_splice_finish: no function pointer found")
		}
	}
	return fn(carg0, carg1, _cerr)
}

//export _goglib_gio2_OutputStream_write_finish
func _goglib_gio2_OutputStream_write_finish(carg0 *C.GOutputStream, carg1 *C.GAsyncResult, _cerr **C.GError) (cret C.gssize) {
	var fn func(carg0 *C.GOutputStream, carg1 *C.GAsyncResult, _cerr **C.GError) (cret C.gssize)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_OutputStream_write_finish").(func(carg0 *C.GOutputStream, carg1 *C.GAsyncResult, _cerr **C.GError) (cret C.gssize))
		if fn == nil {
			panic("_goglib_gio2_OutputStream_write_finish: no function pointer found")
		}
	}
	return fn(carg0, carg1, _cerr)
}

//export _goglib_gio2_OutputStream_write_fn
func _goglib_gio2_OutputStream_write_fn(carg0 *C.GOutputStream, carg1 unsafe.Pointer, carg2 C.gsize, carg3 *C.GCancellable, _cerr **C.GError) (cret C.gssize) {
	var fn func(carg0 *C.GOutputStream, carg1 unsafe.Pointer, carg2 C.gsize, carg3 *C.GCancellable, _cerr **C.GError) (cret C.gssize)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_OutputStream_write_fn").(func(carg0 *C.GOutputStream, carg1 unsafe.Pointer, carg2 C.gsize, carg3 *C.GCancellable, _cerr **C.GError) (cret C.gssize))
		if fn == nil {
			panic("_goglib_gio2_OutputStream_write_fn: no function pointer found")
		}
	}
	return fn(carg0, carg1, carg2, carg3, _cerr)
}

//export _goglib_gio2_OutputStream_writev_finish
func _goglib_gio2_OutputStream_writev_finish(carg0 *C.GOutputStream, carg1 *C.GAsyncResult, carg2 *C.gsize, _cerr **C.GError) (cret C.gboolean) {
	var fn func(carg0 *C.GOutputStream, carg1 *C.GAsyncResult, carg2 *C.gsize, _cerr **C.GError) (cret C.gboolean)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_OutputStream_writev_finish").(func(carg0 *C.GOutputStream, carg1 *C.GAsyncResult, carg2 *C.gsize, _cerr **C.GError) (cret C.gboolean))
		if fn == nil {
			panic("_goglib_gio2_OutputStream_writev_finish: no function pointer found")
		}
	}
	return fn(carg0, carg1, carg2, _cerr)
}

//export _goglib_gio2_Permission_acquire
func _goglib_gio2_Permission_acquire(carg0 *C.GPermission, carg1 *C.GCancellable, _cerr **C.GError) (cret C.gboolean) {
	var fn func(carg0 *C.GPermission, carg1 *C.GCancellable, _cerr **C.GError) (cret C.gboolean)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_Permission_acquire").(func(carg0 *C.GPermission, carg1 *C.GCancellable, _cerr **C.GError) (cret C.gboolean))
		if fn == nil {
			panic("_goglib_gio2_Permission_acquire: no function pointer found")
		}
	}
	return fn(carg0, carg1, _cerr)
}

//export _goglib_gio2_Permission_acquire_finish
func _goglib_gio2_Permission_acquire_finish(carg0 *C.GPermission, carg1 *C.GAsyncResult, _cerr **C.GError) (cret C.gboolean) {
	var fn func(carg0 *C.GPermission, carg1 *C.GAsyncResult, _cerr **C.GError) (cret C.gboolean)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_Permission_acquire_finish").(func(carg0 *C.GPermission, carg1 *C.GAsyncResult, _cerr **C.GError) (cret C.gboolean))
		if fn == nil {
			panic("_goglib_gio2_Permission_acquire_finish: no function pointer found")
		}
	}
	return fn(carg0, carg1, _cerr)
}

//export _goglib_gio2_Permission_release
func _goglib_gio2_Permission_release(carg0 *C.GPermission, carg1 *C.GCancellable, _cerr **C.GError) (cret C.gboolean) {
	var fn func(carg0 *C.GPermission, carg1 *C.GCancellable, _cerr **C.GError) (cret C.gboolean)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_Permission_release").(func(carg0 *C.GPermission, carg1 *C.GCancellable, _cerr **C.GError) (cret C.gboolean))
		if fn == nil {
			panic("_goglib_gio2_Permission_release: no function pointer found")
		}
	}
	return fn(carg0, carg1, _cerr)
}

//export _goglib_gio2_Permission_release_finish
func _goglib_gio2_Permission_release_finish(carg0 *C.GPermission, carg1 *C.GAsyncResult, _cerr **C.GError) (cret C.gboolean) {
	var fn func(carg0 *C.GPermission, carg1 *C.GAsyncResult, _cerr **C.GError) (cret C.gboolean)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_Permission_release_finish").(func(carg0 *C.GPermission, carg1 *C.GAsyncResult, _cerr **C.GError) (cret C.gboolean))
		if fn == nil {
			panic("_goglib_gio2_Permission_release_finish: no function pointer found")
		}
	}
	return fn(carg0, carg1, _cerr)
}

//export _goglib_gio2_Resolver_lookup_by_name
func _goglib_gio2_Resolver_lookup_by_name(carg0 *C.GResolver, carg1 *C.gchar, carg2 *C.GCancellable, _cerr **C.GError) (cret *C.GList) {
	var fn func(carg0 *C.GResolver, carg1 *C.gchar, carg2 *C.GCancellable, _cerr **C.GError) (cret *C.GList)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_Resolver_lookup_by_name").(func(carg0 *C.GResolver, carg1 *C.gchar, carg2 *C.GCancellable, _cerr **C.GError) (cret *C.GList))
		if fn == nil {
			panic("_goglib_gio2_Resolver_lookup_by_name: no function pointer found")
		}
	}
	return fn(carg0, carg1, carg2, _cerr)
}

//export _goglib_gio2_Resolver_lookup_by_name_finish
func _goglib_gio2_Resolver_lookup_by_name_finish(carg0 *C.GResolver, carg1 *C.GAsyncResult, _cerr **C.GError) (cret *C.GList) {
	var fn func(carg0 *C.GResolver, carg1 *C.GAsyncResult, _cerr **C.GError) (cret *C.GList)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_Resolver_lookup_by_name_finish").(func(carg0 *C.GResolver, carg1 *C.GAsyncResult, _cerr **C.GError) (cret *C.GList))
		if fn == nil {
			panic("_goglib_gio2_Resolver_lookup_by_name_finish: no function pointer found")
		}
	}
	return fn(carg0, carg1, _cerr)
}

//export _goglib_gio2_Resolver_lookup_by_name_with_flags
func _goglib_gio2_Resolver_lookup_by_name_with_flags(carg0 *C.GResolver, carg1 *C.gchar, carg2 C.GResolverNameLookupFlags, carg3 *C.GCancellable, _cerr **C.GError) (cret *C.GList) {
	var fn func(carg0 *C.GResolver, carg1 *C.gchar, carg2 C.GResolverNameLookupFlags, carg3 *C.GCancellable, _cerr **C.GError) (cret *C.GList)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_Resolver_lookup_by_name_with_flags").(func(carg0 *C.GResolver, carg1 *C.gchar, carg2 C.GResolverNameLookupFlags, carg3 *C.GCancellable, _cerr **C.GError) (cret *C.GList))
		if fn == nil {
			panic("_goglib_gio2_Resolver_lookup_by_name_with_flags: no function pointer found")
		}
	}
	return fn(carg0, carg1, carg2, carg3, _cerr)
}

//export _goglib_gio2_Resolver_lookup_by_name_with_flags_finish
func _goglib_gio2_Resolver_lookup_by_name_with_flags_finish(carg0 *C.GResolver, carg1 *C.GAsyncResult, _cerr **C.GError) (cret *C.GList) {
	var fn func(carg0 *C.GResolver, carg1 *C.GAsyncResult, _cerr **C.GError) (cret *C.GList)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_Resolver_lookup_by_name_with_flags_finish").(func(carg0 *C.GResolver, carg1 *C.GAsyncResult, _cerr **C.GError) (cret *C.GList))
		if fn == nil {
			panic("_goglib_gio2_Resolver_lookup_by_name_with_flags_finish: no function pointer found")
		}
	}
	return fn(carg0, carg1, _cerr)
}

//export _goglib_gio2_Resolver_lookup_service_finish
func _goglib_gio2_Resolver_lookup_service_finish(carg0 *C.GResolver, carg1 *C.GAsyncResult, _cerr **C.GError) (cret *C.GList) {
	var fn func(carg0 *C.GResolver, carg1 *C.GAsyncResult, _cerr **C.GError) (cret *C.GList)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_Resolver_lookup_service_finish").(func(carg0 *C.GResolver, carg1 *C.GAsyncResult, _cerr **C.GError) (cret *C.GList))
		if fn == nil {
			panic("_goglib_gio2_Resolver_lookup_service_finish: no function pointer found")
		}
	}
	return fn(carg0, carg1, _cerr)
}

//export _goglib_gio2_Resolver_reload
func _goglib_gio2_Resolver_reload(carg0 *C.GResolver) {
	var fn func(carg0 *C.GResolver)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_Resolver_reload").(func(carg0 *C.GResolver))
		if fn == nil {
			panic("_goglib_gio2_Resolver_reload: no function pointer found")
		}
	}
	fn(carg0)
}

//export _goglib_gio2_Settings_change_event
func _goglib_gio2_Settings_change_event(carg0 *C.GSettings, carg1 *C.GQuark, carg2 C.gint) (cret C.gboolean) {
	var fn func(carg0 *C.GSettings, carg1 *C.GQuark, carg2 C.gint) (cret C.gboolean)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_Settings_change_event").(func(carg0 *C.GSettings, carg1 *C.GQuark, carg2 C.gint) (cret C.gboolean))
		if fn == nil {
			panic("_goglib_gio2_Settings_change_event: no function pointer found")
		}
	}
	return fn(carg0, carg1, carg2)
}

//export _goglib_gio2_Settings_changed
func _goglib_gio2_Settings_changed(carg0 *C.GSettings, carg1 *C.gchar) {
	var fn func(carg0 *C.GSettings, carg1 *C.gchar)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_Settings_changed").(func(carg0 *C.GSettings, carg1 *C.gchar))
		if fn == nil {
			panic("_goglib_gio2_Settings_changed: no function pointer found")
		}
	}
	fn(carg0, carg1)
}

//export _goglib_gio2_Settings_writable_change_event
func _goglib_gio2_Settings_writable_change_event(carg0 *C.GSettings, carg1 C.GQuark) (cret C.gboolean) {
	var fn func(carg0 *C.GSettings, carg1 C.GQuark) (cret C.gboolean)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_Settings_writable_change_event").(func(carg0 *C.GSettings, carg1 C.GQuark) (cret C.gboolean))
		if fn == nil {
			panic("_goglib_gio2_Settings_writable_change_event: no function pointer found")
		}
	}
	return fn(carg0, carg1)
}

//export _goglib_gio2_Settings_writable_changed
func _goglib_gio2_Settings_writable_changed(carg0 *C.GSettings, carg1 *C.gchar) {
	var fn func(carg0 *C.GSettings, carg1 *C.gchar)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_Settings_writable_changed").(func(carg0 *C.GSettings, carg1 *C.gchar))
		if fn == nil {
			panic("_goglib_gio2_Settings_writable_changed: no function pointer found")
		}
	}
	fn(carg0, carg1)
}

//export _goglib_gio2_SocketAddress_get_family
func _goglib_gio2_SocketAddress_get_family(carg0 *C.GSocketAddress) (cret C.GSocketFamily) {
	var fn func(carg0 *C.GSocketAddress) (cret C.GSocketFamily)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_SocketAddress_get_family").(func(carg0 *C.GSocketAddress) (cret C.GSocketFamily))
		if fn == nil {
			panic("_goglib_gio2_SocketAddress_get_family: no function pointer found")
		}
	}
	return fn(carg0)
}

//export _goglib_gio2_SocketAddress_get_native_size
func _goglib_gio2_SocketAddress_get_native_size(carg0 *C.GSocketAddress) (cret C.gssize) {
	var fn func(carg0 *C.GSocketAddress) (cret C.gssize)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_SocketAddress_get_native_size").(func(carg0 *C.GSocketAddress) (cret C.gssize))
		if fn == nil {
			panic("_goglib_gio2_SocketAddress_get_native_size: no function pointer found")
		}
	}
	return fn(carg0)
}

//export _goglib_gio2_SocketAddressEnumerator_next
func _goglib_gio2_SocketAddressEnumerator_next(carg0 *C.GSocketAddressEnumerator, carg1 *C.GCancellable, _cerr **C.GError) (cret *C.GSocketAddress) {
	var fn func(carg0 *C.GSocketAddressEnumerator, carg1 *C.GCancellable, _cerr **C.GError) (cret *C.GSocketAddress)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_SocketAddressEnumerator_next").(func(carg0 *C.GSocketAddressEnumerator, carg1 *C.GCancellable, _cerr **C.GError) (cret *C.GSocketAddress))
		if fn == nil {
			panic("_goglib_gio2_SocketAddressEnumerator_next: no function pointer found")
		}
	}
	return fn(carg0, carg1, _cerr)
}

//export _goglib_gio2_SocketAddressEnumerator_next_finish
func _goglib_gio2_SocketAddressEnumerator_next_finish(carg0 *C.GSocketAddressEnumerator, carg1 *C.GAsyncResult, _cerr **C.GError) (cret *C.GSocketAddress) {
	var fn func(carg0 *C.GSocketAddressEnumerator, carg1 *C.GAsyncResult, _cerr **C.GError) (cret *C.GSocketAddress)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_SocketAddressEnumerator_next_finish").(func(carg0 *C.GSocketAddressEnumerator, carg1 *C.GAsyncResult, _cerr **C.GError) (cret *C.GSocketAddress))
		if fn == nil {
			panic("_goglib_gio2_SocketAddressEnumerator_next_finish: no function pointer found")
		}
	}
	return fn(carg0, carg1, _cerr)
}

//export _goglib_gio2_SocketClient_event
func _goglib_gio2_SocketClient_event(carg0 *C.GSocketClient, carg1 C.GSocketClientEvent, carg2 *C.GSocketConnectable, carg3 *C.GIOStream) {
	var fn func(carg0 *C.GSocketClient, carg1 C.GSocketClientEvent, carg2 *C.GSocketConnectable, carg3 *C.GIOStream)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_SocketClient_event").(func(carg0 *C.GSocketClient, carg1 C.GSocketClientEvent, carg2 *C.GSocketConnectable, carg3 *C.GIOStream))
		if fn == nil {
			panic("_goglib_gio2_SocketClient_event: no function pointer found")
		}
	}
	fn(carg0, carg1, carg2, carg3)
}

//export _goglib_gio2_SocketControlMessage_get_level
func _goglib_gio2_SocketControlMessage_get_level(carg0 *C.GSocketControlMessage) (cret C.int) {
	var fn func(carg0 *C.GSocketControlMessage) (cret C.int)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_SocketControlMessage_get_level").(func(carg0 *C.GSocketControlMessage) (cret C.int))
		if fn == nil {
			panic("_goglib_gio2_SocketControlMessage_get_level: no function pointer found")
		}
	}
	return fn(carg0)
}

//export _goglib_gio2_SocketControlMessage_get_size
func _goglib_gio2_SocketControlMessage_get_size(carg0 *C.GSocketControlMessage) (cret C.gsize) {
	var fn func(carg0 *C.GSocketControlMessage) (cret C.gsize)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_SocketControlMessage_get_size").(func(carg0 *C.GSocketControlMessage) (cret C.gsize))
		if fn == nil {
			panic("_goglib_gio2_SocketControlMessage_get_size: no function pointer found")
		}
	}
	return fn(carg0)
}

//export _goglib_gio2_SocketControlMessage_get_type
func _goglib_gio2_SocketControlMessage_get_type(carg0 *C.GSocketControlMessage) (cret C.int) {
	var fn func(carg0 *C.GSocketControlMessage) (cret C.int)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_SocketControlMessage_get_type").(func(carg0 *C.GSocketControlMessage) (cret C.int))
		if fn == nil {
			panic("_goglib_gio2_SocketControlMessage_get_type: no function pointer found")
		}
	}
	return fn(carg0)
}

//export _goglib_gio2_SocketListener_changed
func _goglib_gio2_SocketListener_changed(carg0 *C.GSocketListener) {
	var fn func(carg0 *C.GSocketListener)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_SocketListener_changed").(func(carg0 *C.GSocketListener))
		if fn == nil {
			panic("_goglib_gio2_SocketListener_changed: no function pointer found")
		}
	}
	fn(carg0)
}

//export _goglib_gio2_SocketListener_event
func _goglib_gio2_SocketListener_event(carg0 *C.GSocketListener, carg1 C.GSocketListenerEvent, carg2 *C.GSocket) {
	var fn func(carg0 *C.GSocketListener, carg1 C.GSocketListenerEvent, carg2 *C.GSocket)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_SocketListener_event").(func(carg0 *C.GSocketListener, carg1 C.GSocketListenerEvent, carg2 *C.GSocket))
		if fn == nil {
			panic("_goglib_gio2_SocketListener_event: no function pointer found")
		}
	}
	fn(carg0, carg1, carg2)
}

//export _goglib_gio2_SocketService_incoming
func _goglib_gio2_SocketService_incoming(carg0 *C.GSocketService, carg1 *C.GSocketConnection, carg2 *C.GObject) (cret C.gboolean) {
	var fn func(carg0 *C.GSocketService, carg1 *C.GSocketConnection, carg2 *C.GObject) (cret C.gboolean)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_SocketService_incoming").(func(carg0 *C.GSocketService, carg1 *C.GSocketConnection, carg2 *C.GObject) (cret C.gboolean))
		if fn == nil {
			panic("_goglib_gio2_SocketService_incoming: no function pointer found")
		}
	}
	return fn(carg0, carg1, carg2)
}

//export _goglib_gio2_ThreadedSocketService_run
func _goglib_gio2_ThreadedSocketService_run(carg0 *C.GThreadedSocketService, carg1 *C.GSocketConnection, carg2 *C.GObject) (cret C.gboolean) {
	var fn func(carg0 *C.GThreadedSocketService, carg1 *C.GSocketConnection, carg2 *C.GObject) (cret C.gboolean)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_ThreadedSocketService_run").(func(carg0 *C.GThreadedSocketService, carg1 *C.GSocketConnection, carg2 *C.GObject) (cret C.gboolean))
		if fn == nil {
			panic("_goglib_gio2_ThreadedSocketService_run: no function pointer found")
		}
	}
	return fn(carg0, carg1, carg2)
}

//export _goglib_gio2_TlsCertificate_verify
func _goglib_gio2_TlsCertificate_verify(carg0 *C.GTlsCertificate, carg1 *C.GSocketConnectable, carg2 *C.GTlsCertificate) (cret C.GTlsCertificateFlags) {
	var fn func(carg0 *C.GTlsCertificate, carg1 *C.GSocketConnectable, carg2 *C.GTlsCertificate) (cret C.GTlsCertificateFlags)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_TlsCertificate_verify").(func(carg0 *C.GTlsCertificate, carg1 *C.GSocketConnectable, carg2 *C.GTlsCertificate) (cret C.GTlsCertificateFlags))
		if fn == nil {
			panic("_goglib_gio2_TlsCertificate_verify: no function pointer found")
		}
	}
	return fn(carg0, carg1, carg2)
}

//export _goglib_gio2_TlsConnection_accept_certificate
func _goglib_gio2_TlsConnection_accept_certificate(carg0 *C.GTlsConnection, carg1 *C.GTlsCertificate, carg2 C.GTlsCertificateFlags) (cret C.gboolean) {
	var fn func(carg0 *C.GTlsConnection, carg1 *C.GTlsCertificate, carg2 C.GTlsCertificateFlags) (cret C.gboolean)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_TlsConnection_accept_certificate").(func(carg0 *C.GTlsConnection, carg1 *C.GTlsCertificate, carg2 C.GTlsCertificateFlags) (cret C.gboolean))
		if fn == nil {
			panic("_goglib_gio2_TlsConnection_accept_certificate: no function pointer found")
		}
	}
	return fn(carg0, carg1, carg2)
}

//export _goglib_gio2_TlsConnection_get_negotiated_protocol
func _goglib_gio2_TlsConnection_get_negotiated_protocol(carg0 *C.GTlsConnection) (cret *C.gchar) {
	var fn func(carg0 *C.GTlsConnection) (cret *C.gchar)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_TlsConnection_get_negotiated_protocol").(func(carg0 *C.GTlsConnection) (cret *C.gchar))
		if fn == nil {
			panic("_goglib_gio2_TlsConnection_get_negotiated_protocol: no function pointer found")
		}
	}
	return fn(carg0)
}

//export _goglib_gio2_TlsConnection_handshake
func _goglib_gio2_TlsConnection_handshake(carg0 *C.GTlsConnection, carg1 *C.GCancellable, _cerr **C.GError) (cret C.gboolean) {
	var fn func(carg0 *C.GTlsConnection, carg1 *C.GCancellable, _cerr **C.GError) (cret C.gboolean)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_TlsConnection_handshake").(func(carg0 *C.GTlsConnection, carg1 *C.GCancellable, _cerr **C.GError) (cret C.gboolean))
		if fn == nil {
			panic("_goglib_gio2_TlsConnection_handshake: no function pointer found")
		}
	}
	return fn(carg0, carg1, _cerr)
}

//export _goglib_gio2_TlsConnection_handshake_finish
func _goglib_gio2_TlsConnection_handshake_finish(carg0 *C.GTlsConnection, carg1 *C.GAsyncResult, _cerr **C.GError) (cret C.gboolean) {
	var fn func(carg0 *C.GTlsConnection, carg1 *C.GAsyncResult, _cerr **C.GError) (cret C.gboolean)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_TlsConnection_handshake_finish").(func(carg0 *C.GTlsConnection, carg1 *C.GAsyncResult, _cerr **C.GError) (cret C.gboolean))
		if fn == nil {
			panic("_goglib_gio2_TlsConnection_handshake_finish: no function pointer found")
		}
	}
	return fn(carg0, carg1, _cerr)
}

//export _goglib_gio2_TlsDatabase_lookup_certificate_for_handle
func _goglib_gio2_TlsDatabase_lookup_certificate_for_handle(carg0 *C.GTlsDatabase, carg1 *C.gchar, carg2 *C.GTlsInteraction, carg3 C.GTlsDatabaseLookupFlags, carg4 *C.GCancellable, _cerr **C.GError) (cret *C.GTlsCertificate) {
	var fn func(carg0 *C.GTlsDatabase, carg1 *C.gchar, carg2 *C.GTlsInteraction, carg3 C.GTlsDatabaseLookupFlags, carg4 *C.GCancellable, _cerr **C.GError) (cret *C.GTlsCertificate)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_TlsDatabase_lookup_certificate_for_handle").(func(carg0 *C.GTlsDatabase, carg1 *C.gchar, carg2 *C.GTlsInteraction, carg3 C.GTlsDatabaseLookupFlags, carg4 *C.GCancellable, _cerr **C.GError) (cret *C.GTlsCertificate))
		if fn == nil {
			panic("_goglib_gio2_TlsDatabase_lookup_certificate_for_handle: no function pointer found")
		}
	}
	return fn(carg0, carg1, carg2, carg3, carg4, _cerr)
}

//export _goglib_gio2_TlsDatabase_lookup_certificate_for_handle_finish
func _goglib_gio2_TlsDatabase_lookup_certificate_for_handle_finish(carg0 *C.GTlsDatabase, carg1 *C.GAsyncResult, _cerr **C.GError) (cret *C.GTlsCertificate) {
	var fn func(carg0 *C.GTlsDatabase, carg1 *C.GAsyncResult, _cerr **C.GError) (cret *C.GTlsCertificate)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_TlsDatabase_lookup_certificate_for_handle_finish").(func(carg0 *C.GTlsDatabase, carg1 *C.GAsyncResult, _cerr **C.GError) (cret *C.GTlsCertificate))
		if fn == nil {
			panic("_goglib_gio2_TlsDatabase_lookup_certificate_for_handle_finish: no function pointer found")
		}
	}
	return fn(carg0, carg1, _cerr)
}

//export _goglib_gio2_TlsDatabase_lookup_certificate_issuer
func _goglib_gio2_TlsDatabase_lookup_certificate_issuer(carg0 *C.GTlsDatabase, carg1 *C.GTlsCertificate, carg2 *C.GTlsInteraction, carg3 C.GTlsDatabaseLookupFlags, carg4 *C.GCancellable, _cerr **C.GError) (cret *C.GTlsCertificate) {
	var fn func(carg0 *C.GTlsDatabase, carg1 *C.GTlsCertificate, carg2 *C.GTlsInteraction, carg3 C.GTlsDatabaseLookupFlags, carg4 *C.GCancellable, _cerr **C.GError) (cret *C.GTlsCertificate)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_TlsDatabase_lookup_certificate_issuer").(func(carg0 *C.GTlsDatabase, carg1 *C.GTlsCertificate, carg2 *C.GTlsInteraction, carg3 C.GTlsDatabaseLookupFlags, carg4 *C.GCancellable, _cerr **C.GError) (cret *C.GTlsCertificate))
		if fn == nil {
			panic("_goglib_gio2_TlsDatabase_lookup_certificate_issuer: no function pointer found")
		}
	}
	return fn(carg0, carg1, carg2, carg3, carg4, _cerr)
}

//export _goglib_gio2_TlsDatabase_lookup_certificate_issuer_finish
func _goglib_gio2_TlsDatabase_lookup_certificate_issuer_finish(carg0 *C.GTlsDatabase, carg1 *C.GAsyncResult, _cerr **C.GError) (cret *C.GTlsCertificate) {
	var fn func(carg0 *C.GTlsDatabase, carg1 *C.GAsyncResult, _cerr **C.GError) (cret *C.GTlsCertificate)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_TlsDatabase_lookup_certificate_issuer_finish").(func(carg0 *C.GTlsDatabase, carg1 *C.GAsyncResult, _cerr **C.GError) (cret *C.GTlsCertificate))
		if fn == nil {
			panic("_goglib_gio2_TlsDatabase_lookup_certificate_issuer_finish: no function pointer found")
		}
	}
	return fn(carg0, carg1, _cerr)
}

//export _goglib_gio2_TlsDatabase_lookup_certificates_issued_by_finish
func _goglib_gio2_TlsDatabase_lookup_certificates_issued_by_finish(carg0 *C.GTlsDatabase, carg1 *C.GAsyncResult, _cerr **C.GError) (cret *C.GList) {
	var fn func(carg0 *C.GTlsDatabase, carg1 *C.GAsyncResult, _cerr **C.GError) (cret *C.GList)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_TlsDatabase_lookup_certificates_issued_by_finish").(func(carg0 *C.GTlsDatabase, carg1 *C.GAsyncResult, _cerr **C.GError) (cret *C.GList))
		if fn == nil {
			panic("_goglib_gio2_TlsDatabase_lookup_certificates_issued_by_finish: no function pointer found")
		}
	}
	return fn(carg0, carg1, _cerr)
}

//export _goglib_gio2_TlsDatabase_verify_chain
func _goglib_gio2_TlsDatabase_verify_chain(carg0 *C.GTlsDatabase, carg1 *C.GTlsCertificate, carg2 *C.gchar, carg3 *C.GSocketConnectable, carg4 *C.GTlsInteraction, carg5 C.GTlsDatabaseVerifyFlags, carg6 *C.GCancellable, _cerr **C.GError) (cret C.GTlsCertificateFlags) {
	var fn func(carg0 *C.GTlsDatabase, carg1 *C.GTlsCertificate, carg2 *C.gchar, carg3 *C.GSocketConnectable, carg4 *C.GTlsInteraction, carg5 C.GTlsDatabaseVerifyFlags, carg6 *C.GCancellable, _cerr **C.GError) (cret C.GTlsCertificateFlags)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_TlsDatabase_verify_chain").(func(carg0 *C.GTlsDatabase, carg1 *C.GTlsCertificate, carg2 *C.gchar, carg3 *C.GSocketConnectable, carg4 *C.GTlsInteraction, carg5 C.GTlsDatabaseVerifyFlags, carg6 *C.GCancellable, _cerr **C.GError) (cret C.GTlsCertificateFlags))
		if fn == nil {
			panic("_goglib_gio2_TlsDatabase_verify_chain: no function pointer found")
		}
	}
	return fn(carg0, carg1, carg2, carg3, carg4, carg5, carg6, _cerr)
}

//export _goglib_gio2_TlsDatabase_verify_chain_finish
func _goglib_gio2_TlsDatabase_verify_chain_finish(carg0 *C.GTlsDatabase, carg1 *C.GAsyncResult, _cerr **C.GError) (cret C.GTlsCertificateFlags) {
	var fn func(carg0 *C.GTlsDatabase, carg1 *C.GAsyncResult, _cerr **C.GError) (cret C.GTlsCertificateFlags)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_TlsDatabase_verify_chain_finish").(func(carg0 *C.GTlsDatabase, carg1 *C.GAsyncResult, _cerr **C.GError) (cret C.GTlsCertificateFlags))
		if fn == nil {
			panic("_goglib_gio2_TlsDatabase_verify_chain_finish: no function pointer found")
		}
	}
	return fn(carg0, carg1, _cerr)
}

//export _goglib_gio2_TlsInteraction_ask_password
func _goglib_gio2_TlsInteraction_ask_password(carg0 *C.GTlsInteraction, carg1 *C.GTlsPassword, carg2 *C.GCancellable, _cerr **C.GError) (cret C.GTlsInteractionResult) {
	var fn func(carg0 *C.GTlsInteraction, carg1 *C.GTlsPassword, carg2 *C.GCancellable, _cerr **C.GError) (cret C.GTlsInteractionResult)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_TlsInteraction_ask_password").(func(carg0 *C.GTlsInteraction, carg1 *C.GTlsPassword, carg2 *C.GCancellable, _cerr **C.GError) (cret C.GTlsInteractionResult))
		if fn == nil {
			panic("_goglib_gio2_TlsInteraction_ask_password: no function pointer found")
		}
	}
	return fn(carg0, carg1, carg2, _cerr)
}

//export _goglib_gio2_TlsInteraction_ask_password_finish
func _goglib_gio2_TlsInteraction_ask_password_finish(carg0 *C.GTlsInteraction, carg1 *C.GAsyncResult, _cerr **C.GError) (cret C.GTlsInteractionResult) {
	var fn func(carg0 *C.GTlsInteraction, carg1 *C.GAsyncResult, _cerr **C.GError) (cret C.GTlsInteractionResult)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_TlsInteraction_ask_password_finish").(func(carg0 *C.GTlsInteraction, carg1 *C.GAsyncResult, _cerr **C.GError) (cret C.GTlsInteractionResult))
		if fn == nil {
			panic("_goglib_gio2_TlsInteraction_ask_password_finish: no function pointer found")
		}
	}
	return fn(carg0, carg1, _cerr)
}

//export _goglib_gio2_TlsInteraction_request_certificate
func _goglib_gio2_TlsInteraction_request_certificate(carg0 *C.GTlsInteraction, carg1 *C.GTlsConnection, carg2 C.GTlsCertificateRequestFlags, carg3 *C.GCancellable, _cerr **C.GError) (cret C.GTlsInteractionResult) {
	var fn func(carg0 *C.GTlsInteraction, carg1 *C.GTlsConnection, carg2 C.GTlsCertificateRequestFlags, carg3 *C.GCancellable, _cerr **C.GError) (cret C.GTlsInteractionResult)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_TlsInteraction_request_certificate").(func(carg0 *C.GTlsInteraction, carg1 *C.GTlsConnection, carg2 C.GTlsCertificateRequestFlags, carg3 *C.GCancellable, _cerr **C.GError) (cret C.GTlsInteractionResult))
		if fn == nil {
			panic("_goglib_gio2_TlsInteraction_request_certificate: no function pointer found")
		}
	}
	return fn(carg0, carg1, carg2, carg3, _cerr)
}

//export _goglib_gio2_TlsInteraction_request_certificate_finish
func _goglib_gio2_TlsInteraction_request_certificate_finish(carg0 *C.GTlsInteraction, carg1 *C.GAsyncResult, _cerr **C.GError) (cret C.GTlsInteractionResult) {
	var fn func(carg0 *C.GTlsInteraction, carg1 *C.GAsyncResult, _cerr **C.GError) (cret C.GTlsInteractionResult)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_TlsInteraction_request_certificate_finish").(func(carg0 *C.GTlsInteraction, carg1 *C.GAsyncResult, _cerr **C.GError) (cret C.GTlsInteractionResult))
		if fn == nil {
			panic("_goglib_gio2_TlsInteraction_request_certificate_finish: no function pointer found")
		}
	}
	return fn(carg0, carg1, _cerr)
}

//export _goglib_gio2_TlsPassword_get_default_warning
func _goglib_gio2_TlsPassword_get_default_warning(carg0 *C.GTlsPassword) (cret *C.gchar) {
	var fn func(carg0 *C.GTlsPassword) (cret *C.gchar)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_TlsPassword_get_default_warning").(func(carg0 *C.GTlsPassword) (cret *C.gchar))
		if fn == nil {
			panic("_goglib_gio2_TlsPassword_get_default_warning: no function pointer found")
		}
	}
	return fn(carg0)
}

//export _goglib_gio2_TlsPassword_get_value
func _goglib_gio2_TlsPassword_get_value(carg0 *C.GTlsPassword, carg1 *C.gsize) (cret *C.guchar) {
	var fn func(carg0 *C.GTlsPassword, carg1 *C.gsize) (cret *C.guchar)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_TlsPassword_get_value").(func(carg0 *C.GTlsPassword, carg1 *C.gsize) (cret *C.guchar))
		if fn == nil {
			panic("_goglib_gio2_TlsPassword_get_value: no function pointer found")
		}
	}
	return fn(carg0, carg1)
}

//export _goglib_gio2_Vfs_add_writable_namespaces
func _goglib_gio2_Vfs_add_writable_namespaces(carg0 *C.GVfs, carg1 *C.GFileAttributeInfoList) {
	var fn func(carg0 *C.GVfs, carg1 *C.GFileAttributeInfoList)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_Vfs_add_writable_namespaces").(func(carg0 *C.GVfs, carg1 *C.GFileAttributeInfoList))
		if fn == nil {
			panic("_goglib_gio2_Vfs_add_writable_namespaces: no function pointer found")
		}
	}
	fn(carg0, carg1)
}

//export _goglib_gio2_Vfs_get_file_for_path
func _goglib_gio2_Vfs_get_file_for_path(carg0 *C.GVfs, carg1 *C.char) (cret *C.GFile) {
	var fn func(carg0 *C.GVfs, carg1 *C.char) (cret *C.GFile)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_Vfs_get_file_for_path").(func(carg0 *C.GVfs, carg1 *C.char) (cret *C.GFile))
		if fn == nil {
			panic("_goglib_gio2_Vfs_get_file_for_path: no function pointer found")
		}
	}
	return fn(carg0, carg1)
}

//export _goglib_gio2_Vfs_get_file_for_uri
func _goglib_gio2_Vfs_get_file_for_uri(carg0 *C.GVfs, carg1 *C.char) (cret *C.GFile) {
	var fn func(carg0 *C.GVfs, carg1 *C.char) (cret *C.GFile)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_Vfs_get_file_for_uri").(func(carg0 *C.GVfs, carg1 *C.char) (cret *C.GFile))
		if fn == nil {
			panic("_goglib_gio2_Vfs_get_file_for_uri: no function pointer found")
		}
	}
	return fn(carg0, carg1)
}

//export _goglib_gio2_Vfs_get_supported_uri_schemes
func _goglib_gio2_Vfs_get_supported_uri_schemes(carg0 *C.GVfs) (cret **C.gchar) {
	var fn func(carg0 *C.GVfs) (cret **C.gchar)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_Vfs_get_supported_uri_schemes").(func(carg0 *C.GVfs) (cret **C.gchar))
		if fn == nil {
			panic("_goglib_gio2_Vfs_get_supported_uri_schemes: no function pointer found")
		}
	}
	return fn(carg0)
}

//export _goglib_gio2_Vfs_is_active
func _goglib_gio2_Vfs_is_active(carg0 *C.GVfs) (cret C.gboolean) {
	var fn func(carg0 *C.GVfs) (cret C.gboolean)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_Vfs_is_active").(func(carg0 *C.GVfs) (cret C.gboolean))
		if fn == nil {
			panic("_goglib_gio2_Vfs_is_active: no function pointer found")
		}
	}
	return fn(carg0)
}

//export _goglib_gio2_Vfs_local_file_moved
func _goglib_gio2_Vfs_local_file_moved(carg0 *C.GVfs, carg1 *C.char, carg2 *C.char) {
	var fn func(carg0 *C.GVfs, carg1 *C.char, carg2 *C.char)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_Vfs_local_file_moved").(func(carg0 *C.GVfs, carg1 *C.char, carg2 *C.char))
		if fn == nil {
			panic("_goglib_gio2_Vfs_local_file_moved: no function pointer found")
		}
	}
	fn(carg0, carg1, carg2)
}

//export _goglib_gio2_Vfs_local_file_removed
func _goglib_gio2_Vfs_local_file_removed(carg0 *C.GVfs, carg1 *C.char) {
	var fn func(carg0 *C.GVfs, carg1 *C.char)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_Vfs_local_file_removed").(func(carg0 *C.GVfs, carg1 *C.char))
		if fn == nil {
			panic("_goglib_gio2_Vfs_local_file_removed: no function pointer found")
		}
	}
	fn(carg0, carg1)
}

//export _goglib_gio2_Vfs_local_file_set_attributes
func _goglib_gio2_Vfs_local_file_set_attributes(carg0 *C.GVfs, carg1 *C.char, carg2 *C.GFileInfo, carg3 C.GFileQueryInfoFlags, carg4 *C.GCancellable, _cerr **C.GError) (cret C.gboolean) {
	var fn func(carg0 *C.GVfs, carg1 *C.char, carg2 *C.GFileInfo, carg3 C.GFileQueryInfoFlags, carg4 *C.GCancellable, _cerr **C.GError) (cret C.gboolean)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_Vfs_local_file_set_attributes").(func(carg0 *C.GVfs, carg1 *C.char, carg2 *C.GFileInfo, carg3 C.GFileQueryInfoFlags, carg4 *C.GCancellable, _cerr **C.GError) (cret C.gboolean))
		if fn == nil {
			panic("_goglib_gio2_Vfs_local_file_set_attributes: no function pointer found")
		}
	}
	return fn(carg0, carg1, carg2, carg3, carg4, _cerr)
}

//export _goglib_gio2_Vfs_parse_name
func _goglib_gio2_Vfs_parse_name(carg0 *C.GVfs, carg1 *C.char) (cret *C.GFile) {
	var fn func(carg0 *C.GVfs, carg1 *C.char) (cret *C.GFile)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_Vfs_parse_name").(func(carg0 *C.GVfs, carg1 *C.char) (cret *C.GFile))
		if fn == nil {
			panic("_goglib_gio2_Vfs_parse_name: no function pointer found")
		}
	}
	return fn(carg0, carg1)
}

//export _goglib_gio2_VolumeMonitor_drive_changed
func _goglib_gio2_VolumeMonitor_drive_changed(carg0 *C.GVolumeMonitor, carg1 *C.GDrive) {
	var fn func(carg0 *C.GVolumeMonitor, carg1 *C.GDrive)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_VolumeMonitor_drive_changed").(func(carg0 *C.GVolumeMonitor, carg1 *C.GDrive))
		if fn == nil {
			panic("_goglib_gio2_VolumeMonitor_drive_changed: no function pointer found")
		}
	}
	fn(carg0, carg1)
}

//export _goglib_gio2_VolumeMonitor_drive_connected
func _goglib_gio2_VolumeMonitor_drive_connected(carg0 *C.GVolumeMonitor, carg1 *C.GDrive) {
	var fn func(carg0 *C.GVolumeMonitor, carg1 *C.GDrive)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_VolumeMonitor_drive_connected").(func(carg0 *C.GVolumeMonitor, carg1 *C.GDrive))
		if fn == nil {
			panic("_goglib_gio2_VolumeMonitor_drive_connected: no function pointer found")
		}
	}
	fn(carg0, carg1)
}

//export _goglib_gio2_VolumeMonitor_drive_disconnected
func _goglib_gio2_VolumeMonitor_drive_disconnected(carg0 *C.GVolumeMonitor, carg1 *C.GDrive) {
	var fn func(carg0 *C.GVolumeMonitor, carg1 *C.GDrive)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_VolumeMonitor_drive_disconnected").(func(carg0 *C.GVolumeMonitor, carg1 *C.GDrive))
		if fn == nil {
			panic("_goglib_gio2_VolumeMonitor_drive_disconnected: no function pointer found")
		}
	}
	fn(carg0, carg1)
}

//export _goglib_gio2_VolumeMonitor_drive_eject_button
func _goglib_gio2_VolumeMonitor_drive_eject_button(carg0 *C.GVolumeMonitor, carg1 *C.GDrive) {
	var fn func(carg0 *C.GVolumeMonitor, carg1 *C.GDrive)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_VolumeMonitor_drive_eject_button").(func(carg0 *C.GVolumeMonitor, carg1 *C.GDrive))
		if fn == nil {
			panic("_goglib_gio2_VolumeMonitor_drive_eject_button: no function pointer found")
		}
	}
	fn(carg0, carg1)
}

//export _goglib_gio2_VolumeMonitor_drive_stop_button
func _goglib_gio2_VolumeMonitor_drive_stop_button(carg0 *C.GVolumeMonitor, carg1 *C.GDrive) {
	var fn func(carg0 *C.GVolumeMonitor, carg1 *C.GDrive)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_VolumeMonitor_drive_stop_button").(func(carg0 *C.GVolumeMonitor, carg1 *C.GDrive))
		if fn == nil {
			panic("_goglib_gio2_VolumeMonitor_drive_stop_button: no function pointer found")
		}
	}
	fn(carg0, carg1)
}

//export _goglib_gio2_VolumeMonitor_get_connected_drives
func _goglib_gio2_VolumeMonitor_get_connected_drives(carg0 *C.GVolumeMonitor) (cret *C.GList) {
	var fn func(carg0 *C.GVolumeMonitor) (cret *C.GList)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_VolumeMonitor_get_connected_drives").(func(carg0 *C.GVolumeMonitor) (cret *C.GList))
		if fn == nil {
			panic("_goglib_gio2_VolumeMonitor_get_connected_drives: no function pointer found")
		}
	}
	return fn(carg0)
}

//export _goglib_gio2_VolumeMonitor_get_mount_for_uuid
func _goglib_gio2_VolumeMonitor_get_mount_for_uuid(carg0 *C.GVolumeMonitor, carg1 *C.char) (cret *C.GMount) {
	var fn func(carg0 *C.GVolumeMonitor, carg1 *C.char) (cret *C.GMount)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_VolumeMonitor_get_mount_for_uuid").(func(carg0 *C.GVolumeMonitor, carg1 *C.char) (cret *C.GMount))
		if fn == nil {
			panic("_goglib_gio2_VolumeMonitor_get_mount_for_uuid: no function pointer found")
		}
	}
	return fn(carg0, carg1)
}

//export _goglib_gio2_VolumeMonitor_get_mounts
func _goglib_gio2_VolumeMonitor_get_mounts(carg0 *C.GVolumeMonitor) (cret *C.GList) {
	var fn func(carg0 *C.GVolumeMonitor) (cret *C.GList)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_VolumeMonitor_get_mounts").(func(carg0 *C.GVolumeMonitor) (cret *C.GList))
		if fn == nil {
			panic("_goglib_gio2_VolumeMonitor_get_mounts: no function pointer found")
		}
	}
	return fn(carg0)
}

//export _goglib_gio2_VolumeMonitor_get_volume_for_uuid
func _goglib_gio2_VolumeMonitor_get_volume_for_uuid(carg0 *C.GVolumeMonitor, carg1 *C.char) (cret *C.GVolume) {
	var fn func(carg0 *C.GVolumeMonitor, carg1 *C.char) (cret *C.GVolume)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_VolumeMonitor_get_volume_for_uuid").(func(carg0 *C.GVolumeMonitor, carg1 *C.char) (cret *C.GVolume))
		if fn == nil {
			panic("_goglib_gio2_VolumeMonitor_get_volume_for_uuid: no function pointer found")
		}
	}
	return fn(carg0, carg1)
}

//export _goglib_gio2_VolumeMonitor_get_volumes
func _goglib_gio2_VolumeMonitor_get_volumes(carg0 *C.GVolumeMonitor) (cret *C.GList) {
	var fn func(carg0 *C.GVolumeMonitor) (cret *C.GList)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_VolumeMonitor_get_volumes").(func(carg0 *C.GVolumeMonitor) (cret *C.GList))
		if fn == nil {
			panic("_goglib_gio2_VolumeMonitor_get_volumes: no function pointer found")
		}
	}
	return fn(carg0)
}

//export _goglib_gio2_VolumeMonitor_mount_added
func _goglib_gio2_VolumeMonitor_mount_added(carg0 *C.GVolumeMonitor, carg1 *C.GMount) {
	var fn func(carg0 *C.GVolumeMonitor, carg1 *C.GMount)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_VolumeMonitor_mount_added").(func(carg0 *C.GVolumeMonitor, carg1 *C.GMount))
		if fn == nil {
			panic("_goglib_gio2_VolumeMonitor_mount_added: no function pointer found")
		}
	}
	fn(carg0, carg1)
}

//export _goglib_gio2_VolumeMonitor_mount_changed
func _goglib_gio2_VolumeMonitor_mount_changed(carg0 *C.GVolumeMonitor, carg1 *C.GMount) {
	var fn func(carg0 *C.GVolumeMonitor, carg1 *C.GMount)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_VolumeMonitor_mount_changed").(func(carg0 *C.GVolumeMonitor, carg1 *C.GMount))
		if fn == nil {
			panic("_goglib_gio2_VolumeMonitor_mount_changed: no function pointer found")
		}
	}
	fn(carg0, carg1)
}

//export _goglib_gio2_VolumeMonitor_mount_pre_unmount
func _goglib_gio2_VolumeMonitor_mount_pre_unmount(carg0 *C.GVolumeMonitor, carg1 *C.GMount) {
	var fn func(carg0 *C.GVolumeMonitor, carg1 *C.GMount)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_VolumeMonitor_mount_pre_unmount").(func(carg0 *C.GVolumeMonitor, carg1 *C.GMount))
		if fn == nil {
			panic("_goglib_gio2_VolumeMonitor_mount_pre_unmount: no function pointer found")
		}
	}
	fn(carg0, carg1)
}

//export _goglib_gio2_VolumeMonitor_mount_removed
func _goglib_gio2_VolumeMonitor_mount_removed(carg0 *C.GVolumeMonitor, carg1 *C.GMount) {
	var fn func(carg0 *C.GVolumeMonitor, carg1 *C.GMount)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_VolumeMonitor_mount_removed").(func(carg0 *C.GVolumeMonitor, carg1 *C.GMount))
		if fn == nil {
			panic("_goglib_gio2_VolumeMonitor_mount_removed: no function pointer found")
		}
	}
	fn(carg0, carg1)
}

//export _goglib_gio2_VolumeMonitor_volume_added
func _goglib_gio2_VolumeMonitor_volume_added(carg0 *C.GVolumeMonitor, carg1 *C.GVolume) {
	var fn func(carg0 *C.GVolumeMonitor, carg1 *C.GVolume)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_VolumeMonitor_volume_added").(func(carg0 *C.GVolumeMonitor, carg1 *C.GVolume))
		if fn == nil {
			panic("_goglib_gio2_VolumeMonitor_volume_added: no function pointer found")
		}
	}
	fn(carg0, carg1)
}

//export _goglib_gio2_VolumeMonitor_volume_changed
func _goglib_gio2_VolumeMonitor_volume_changed(carg0 *C.GVolumeMonitor, carg1 *C.GVolume) {
	var fn func(carg0 *C.GVolumeMonitor, carg1 *C.GVolume)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_VolumeMonitor_volume_changed").(func(carg0 *C.GVolumeMonitor, carg1 *C.GVolume))
		if fn == nil {
			panic("_goglib_gio2_VolumeMonitor_volume_changed: no function pointer found")
		}
	}
	fn(carg0, carg1)
}

//export _goglib_gio2_VolumeMonitor_volume_removed
func _goglib_gio2_VolumeMonitor_volume_removed(carg0 *C.GVolumeMonitor, carg1 *C.GVolume) {
	var fn func(carg0 *C.GVolumeMonitor, carg1 *C.GVolume)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_VolumeMonitor_volume_removed").(func(carg0 *C.GVolumeMonitor, carg1 *C.GVolume))
		if fn == nil {
			panic("_goglib_gio2_VolumeMonitor_volume_removed: no function pointer found")
		}
	}
	fn(carg0, carg1)
}

//export _goglib_gio2_FileIOStream_can_seek
func _goglib_gio2_FileIOStream_can_seek(carg0 *C.GFileIOStream) (cret C.gboolean) {
	var fn func(carg0 *C.GFileIOStream) (cret C.gboolean)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_FileIOStream_can_seek").(func(carg0 *C.GFileIOStream) (cret C.gboolean))
		if fn == nil {
			panic("_goglib_gio2_FileIOStream_can_seek: no function pointer found")
		}
	}
	return fn(carg0)
}

//export _goglib_gio2_FileIOStream_can_truncate
func _goglib_gio2_FileIOStream_can_truncate(carg0 *C.GFileIOStream) (cret C.gboolean) {
	var fn func(carg0 *C.GFileIOStream) (cret C.gboolean)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_FileIOStream_can_truncate").(func(carg0 *C.GFileIOStream) (cret C.gboolean))
		if fn == nil {
			panic("_goglib_gio2_FileIOStream_can_truncate: no function pointer found")
		}
	}
	return fn(carg0)
}

//export _goglib_gio2_FileIOStream_query_info
func _goglib_gio2_FileIOStream_query_info(carg0 *C.GFileIOStream, carg1 *C.char, carg2 *C.GCancellable, _cerr **C.GError) (cret *C.GFileInfo) {
	var fn func(carg0 *C.GFileIOStream, carg1 *C.char, carg2 *C.GCancellable, _cerr **C.GError) (cret *C.GFileInfo)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_FileIOStream_query_info").(func(carg0 *C.GFileIOStream, carg1 *C.char, carg2 *C.GCancellable, _cerr **C.GError) (cret *C.GFileInfo))
		if fn == nil {
			panic("_goglib_gio2_FileIOStream_query_info: no function pointer found")
		}
	}
	return fn(carg0, carg1, carg2, _cerr)
}

//export _goglib_gio2_FileIOStream_query_info_finish
func _goglib_gio2_FileIOStream_query_info_finish(carg0 *C.GFileIOStream, carg1 *C.GAsyncResult, _cerr **C.GError) (cret *C.GFileInfo) {
	var fn func(carg0 *C.GFileIOStream, carg1 *C.GAsyncResult, _cerr **C.GError) (cret *C.GFileInfo)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_FileIOStream_query_info_finish").(func(carg0 *C.GFileIOStream, carg1 *C.GAsyncResult, _cerr **C.GError) (cret *C.GFileInfo))
		if fn == nil {
			panic("_goglib_gio2_FileIOStream_query_info_finish: no function pointer found")
		}
	}
	return fn(carg0, carg1, _cerr)
}

//export _goglib_gio2_FileIOStream_seek
func _goglib_gio2_FileIOStream_seek(carg0 *C.GFileIOStream, carg1 C.goffset, carg2 C.GSeekType, carg3 *C.GCancellable, _cerr **C.GError) (cret C.gboolean) {
	var fn func(carg0 *C.GFileIOStream, carg1 C.goffset, carg2 C.GSeekType, carg3 *C.GCancellable, _cerr **C.GError) (cret C.gboolean)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_FileIOStream_seek").(func(carg0 *C.GFileIOStream, carg1 C.goffset, carg2 C.GSeekType, carg3 *C.GCancellable, _cerr **C.GError) (cret C.gboolean))
		if fn == nil {
			panic("_goglib_gio2_FileIOStream_seek: no function pointer found")
		}
	}
	return fn(carg0, carg1, carg2, carg3, _cerr)
}

//export _goglib_gio2_FileIOStream_tell
func _goglib_gio2_FileIOStream_tell(carg0 *C.GFileIOStream) (cret C.goffset) {
	var fn func(carg0 *C.GFileIOStream) (cret C.goffset)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_FileIOStream_tell").(func(carg0 *C.GFileIOStream) (cret C.goffset))
		if fn == nil {
			panic("_goglib_gio2_FileIOStream_tell: no function pointer found")
		}
	}
	return fn(carg0)
}

//export _goglib_gio2_FileIOStream_truncate_fn
func _goglib_gio2_FileIOStream_truncate_fn(carg0 *C.GFileIOStream, carg1 C.goffset, carg2 *C.GCancellable, _cerr **C.GError) (cret C.gboolean) {
	var fn func(carg0 *C.GFileIOStream, carg1 C.goffset, carg2 *C.GCancellable, _cerr **C.GError) (cret C.gboolean)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_FileIOStream_truncate_fn").(func(carg0 *C.GFileIOStream, carg1 C.goffset, carg2 *C.GCancellable, _cerr **C.GError) (cret C.gboolean))
		if fn == nil {
			panic("_goglib_gio2_FileIOStream_truncate_fn: no function pointer found")
		}
	}
	return fn(carg0, carg1, carg2, _cerr)
}

//export _goglib_gio2_FileInputStream_can_seek
func _goglib_gio2_FileInputStream_can_seek(carg0 *C.GFileInputStream) (cret C.gboolean) {
	var fn func(carg0 *C.GFileInputStream) (cret C.gboolean)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_FileInputStream_can_seek").(func(carg0 *C.GFileInputStream) (cret C.gboolean))
		if fn == nil {
			panic("_goglib_gio2_FileInputStream_can_seek: no function pointer found")
		}
	}
	return fn(carg0)
}

//export _goglib_gio2_FileInputStream_query_info
func _goglib_gio2_FileInputStream_query_info(carg0 *C.GFileInputStream, carg1 *C.char, carg2 *C.GCancellable, _cerr **C.GError) (cret *C.GFileInfo) {
	var fn func(carg0 *C.GFileInputStream, carg1 *C.char, carg2 *C.GCancellable, _cerr **C.GError) (cret *C.GFileInfo)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_FileInputStream_query_info").(func(carg0 *C.GFileInputStream, carg1 *C.char, carg2 *C.GCancellable, _cerr **C.GError) (cret *C.GFileInfo))
		if fn == nil {
			panic("_goglib_gio2_FileInputStream_query_info: no function pointer found")
		}
	}
	return fn(carg0, carg1, carg2, _cerr)
}

//export _goglib_gio2_FileInputStream_query_info_finish
func _goglib_gio2_FileInputStream_query_info_finish(carg0 *C.GFileInputStream, carg1 *C.GAsyncResult, _cerr **C.GError) (cret *C.GFileInfo) {
	var fn func(carg0 *C.GFileInputStream, carg1 *C.GAsyncResult, _cerr **C.GError) (cret *C.GFileInfo)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_FileInputStream_query_info_finish").(func(carg0 *C.GFileInputStream, carg1 *C.GAsyncResult, _cerr **C.GError) (cret *C.GFileInfo))
		if fn == nil {
			panic("_goglib_gio2_FileInputStream_query_info_finish: no function pointer found")
		}
	}
	return fn(carg0, carg1, _cerr)
}

//export _goglib_gio2_FileInputStream_seek
func _goglib_gio2_FileInputStream_seek(carg0 *C.GFileInputStream, carg1 C.goffset, carg2 C.GSeekType, carg3 *C.GCancellable, _cerr **C.GError) (cret C.gboolean) {
	var fn func(carg0 *C.GFileInputStream, carg1 C.goffset, carg2 C.GSeekType, carg3 *C.GCancellable, _cerr **C.GError) (cret C.gboolean)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_FileInputStream_seek").(func(carg0 *C.GFileInputStream, carg1 C.goffset, carg2 C.GSeekType, carg3 *C.GCancellable, _cerr **C.GError) (cret C.gboolean))
		if fn == nil {
			panic("_goglib_gio2_FileInputStream_seek: no function pointer found")
		}
	}
	return fn(carg0, carg1, carg2, carg3, _cerr)
}

//export _goglib_gio2_FileInputStream_tell
func _goglib_gio2_FileInputStream_tell(carg0 *C.GFileInputStream) (cret C.goffset) {
	var fn func(carg0 *C.GFileInputStream) (cret C.goffset)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_FileInputStream_tell").(func(carg0 *C.GFileInputStream) (cret C.goffset))
		if fn == nil {
			panic("_goglib_gio2_FileInputStream_tell: no function pointer found")
		}
	}
	return fn(carg0)
}

//export _goglib_gio2_FileOutputStream_can_seek
func _goglib_gio2_FileOutputStream_can_seek(carg0 *C.GFileOutputStream) (cret C.gboolean) {
	var fn func(carg0 *C.GFileOutputStream) (cret C.gboolean)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_FileOutputStream_can_seek").(func(carg0 *C.GFileOutputStream) (cret C.gboolean))
		if fn == nil {
			panic("_goglib_gio2_FileOutputStream_can_seek: no function pointer found")
		}
	}
	return fn(carg0)
}

//export _goglib_gio2_FileOutputStream_can_truncate
func _goglib_gio2_FileOutputStream_can_truncate(carg0 *C.GFileOutputStream) (cret C.gboolean) {
	var fn func(carg0 *C.GFileOutputStream) (cret C.gboolean)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_FileOutputStream_can_truncate").(func(carg0 *C.GFileOutputStream) (cret C.gboolean))
		if fn == nil {
			panic("_goglib_gio2_FileOutputStream_can_truncate: no function pointer found")
		}
	}
	return fn(carg0)
}

//export _goglib_gio2_FileOutputStream_query_info
func _goglib_gio2_FileOutputStream_query_info(carg0 *C.GFileOutputStream, carg1 *C.char, carg2 *C.GCancellable, _cerr **C.GError) (cret *C.GFileInfo) {
	var fn func(carg0 *C.GFileOutputStream, carg1 *C.char, carg2 *C.GCancellable, _cerr **C.GError) (cret *C.GFileInfo)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_FileOutputStream_query_info").(func(carg0 *C.GFileOutputStream, carg1 *C.char, carg2 *C.GCancellable, _cerr **C.GError) (cret *C.GFileInfo))
		if fn == nil {
			panic("_goglib_gio2_FileOutputStream_query_info: no function pointer found")
		}
	}
	return fn(carg0, carg1, carg2, _cerr)
}

//export _goglib_gio2_FileOutputStream_query_info_finish
func _goglib_gio2_FileOutputStream_query_info_finish(carg0 *C.GFileOutputStream, carg1 *C.GAsyncResult, _cerr **C.GError) (cret *C.GFileInfo) {
	var fn func(carg0 *C.GFileOutputStream, carg1 *C.GAsyncResult, _cerr **C.GError) (cret *C.GFileInfo)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_FileOutputStream_query_info_finish").(func(carg0 *C.GFileOutputStream, carg1 *C.GAsyncResult, _cerr **C.GError) (cret *C.GFileInfo))
		if fn == nil {
			panic("_goglib_gio2_FileOutputStream_query_info_finish: no function pointer found")
		}
	}
	return fn(carg0, carg1, _cerr)
}

//export _goglib_gio2_FileOutputStream_seek
func _goglib_gio2_FileOutputStream_seek(carg0 *C.GFileOutputStream, carg1 C.goffset, carg2 C.GSeekType, carg3 *C.GCancellable, _cerr **C.GError) (cret C.gboolean) {
	var fn func(carg0 *C.GFileOutputStream, carg1 C.goffset, carg2 C.GSeekType, carg3 *C.GCancellable, _cerr **C.GError) (cret C.gboolean)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_FileOutputStream_seek").(func(carg0 *C.GFileOutputStream, carg1 C.goffset, carg2 C.GSeekType, carg3 *C.GCancellable, _cerr **C.GError) (cret C.gboolean))
		if fn == nil {
			panic("_goglib_gio2_FileOutputStream_seek: no function pointer found")
		}
	}
	return fn(carg0, carg1, carg2, carg3, _cerr)
}

//export _goglib_gio2_FileOutputStream_tell
func _goglib_gio2_FileOutputStream_tell(carg0 *C.GFileOutputStream) (cret C.goffset) {
	var fn func(carg0 *C.GFileOutputStream) (cret C.goffset)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_FileOutputStream_tell").(func(carg0 *C.GFileOutputStream) (cret C.goffset))
		if fn == nil {
			panic("_goglib_gio2_FileOutputStream_tell: no function pointer found")
		}
	}
	return fn(carg0)
}

//export _goglib_gio2_FileOutputStream_truncate_fn
func _goglib_gio2_FileOutputStream_truncate_fn(carg0 *C.GFileOutputStream, carg1 C.goffset, carg2 *C.GCancellable, _cerr **C.GError) (cret C.gboolean) {
	var fn func(carg0 *C.GFileOutputStream, carg1 C.goffset, carg2 *C.GCancellable, _cerr **C.GError) (cret C.gboolean)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_FileOutputStream_truncate_fn").(func(carg0 *C.GFileOutputStream, carg1 C.goffset, carg2 *C.GCancellable, _cerr **C.GError) (cret C.gboolean))
		if fn == nil {
			panic("_goglib_gio2_FileOutputStream_truncate_fn: no function pointer found")
		}
	}
	return fn(carg0, carg1, carg2, _cerr)
}

//export _goglib_gio2_BufferedInputStream_fill
func _goglib_gio2_BufferedInputStream_fill(carg0 *C.GBufferedInputStream, carg1 C.gssize, carg2 *C.GCancellable, _cerr **C.GError) (cret C.gssize) {
	var fn func(carg0 *C.GBufferedInputStream, carg1 C.gssize, carg2 *C.GCancellable, _cerr **C.GError) (cret C.gssize)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_BufferedInputStream_fill").(func(carg0 *C.GBufferedInputStream, carg1 C.gssize, carg2 *C.GCancellable, _cerr **C.GError) (cret C.gssize))
		if fn == nil {
			panic("_goglib_gio2_BufferedInputStream_fill: no function pointer found")
		}
	}
	return fn(carg0, carg1, carg2, _cerr)
}

//export _goglib_gio2_BufferedInputStream_fill_finish
func _goglib_gio2_BufferedInputStream_fill_finish(carg0 *C.GBufferedInputStream, carg1 *C.GAsyncResult, _cerr **C.GError) (cret C.gssize) {
	var fn func(carg0 *C.GBufferedInputStream, carg1 *C.GAsyncResult, _cerr **C.GError) (cret C.gssize)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_goglib_gio2_BufferedInputStream_fill_finish").(func(carg0 *C.GBufferedInputStream, carg1 *C.GAsyncResult, _cerr **C.GError) (cret C.gssize))
		if fn == nil {
			panic("_goglib_gio2_BufferedInputStream_fill_finish: no function pointer found")
		}
	}
	return fn(carg0, carg1, _cerr)
}

